app:
  docs_url: /docs
  redoc_url: /redoc

logging:
  level: 'INFO'

server:
  cors: ['*',]  # TODO switch to frontend when it will be finished 

data:
  db:
    url: postgresql+asyncpg://postgres:postgres@localhost:5432/exampleapp'
    url_sync: postgresql+psycopg://postgres:postgres@localhost:5432/exampleapp'

services:
  auth:
    expire_min: 1
    refresh_min: 10
