version: '3.7'
services:

  mongo:
    image: mongo:latest
    container_name: exampleapp_auth_mongo
    env_file:
      - .env
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017    # remove in prod, use only if we want to access from outside of docker

  app:
    image: exampleapp_auth_api_image:v1
    container_name: exampleapp_auth_api
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - mongo
    volumes:
      - logdata:/logs/auth
    ports:
      - 8001:8001    # remove in prod, use only if we want to access from outside of docker
    command:
      - /bin/sh
      - -c
      - |
        alembic -c tox.ini upgrade head
        gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8001

volumes:
  logdata:
  mongodbdata:
