version: '3.7'
services:

  mongo:
    image: mongo:latest
    container_name: investapp_auth_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017    # remove in prod, use only if we want to access from outside of docker

  app:
    image: investapp_auth_api_image:v1
    container_name: investapp_auth_api
    environment:
      - APP_MODE=${APP_MODE}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    build:
      context: .
    depends_on:
      - mongo
    volumes:
      - logdata:/logs/auth
    ports:
      - 8001:8001    # remove in prod, use only if we want to access from outside of docker
    command:
      - /bin/sh
      - -c
      - |
        alembic -c tox.ini upgrade head
        gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8001

volumes:
  logdata:
  mongodbdata:
